package com.shopsphere.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RedeemRewardRequest {

    @NotNull(message = "User ID is required")
    private Long userId;

    @NotNull(message = "Points to redeem is required")
    @Min(value = 1, message = "Points must be at least 1")
    private Integer points;

    @NotBlank(message = "Reward name is required")
    private String rewardName;

    private String discountCode; // Generated by backend
}
